import 'server-only';
import type { Readable } from 'node:stream';

/**
 * Where backup archives live.
 *
 * Separate from the CMS media storage on purpose: media is public and served
 * by URL, backups are private and only ever reached through an authenticated,
 * permission-checked route or a short-lived signed URL. The two must not share
 * a bucket or a code path.
 *
 * Every method takes a *key*, never a filesystem path. Implementations are
 * responsible for rejecting a key that tries to escape their own namespace.
 */
export interface BackupStorageProvider {
  readonly kind: 'LOCAL' | 'S3';

  /** Streams an archive in. Returns the size actually written. */
  upload(key: string, body: Readable): Promise<{ size: number }>;

  /** Streams an archive out. Throws when the key does not exist. */
  download(key: string): Promise<Readable>;

  delete(key: string): Promise<void>;

  exists(key: string): Promise<boolean>;

  /**
   * A time-limited URL, when the provider can issue one.
   *
   * Local storage returns null — there is no public origin to sign against, so
   * the caller falls back to the authenticated download route.
   */
  getSignedDownloadUrl(key: string, expiresInSeconds: number): Promise<string | null>;

  list(prefix?: string): Promise<Array<{ key: string; size: number; modifiedAt: Date }>>;

  /** Cheap round-trip used by the "Test connection" button. */
  healthCheck(): Promise<{ ok: true } | { ok: false; error: string }>;
}

/**
 * Keys are generated by this application, never supplied by a user, but they
 * are validated anyway: a key reaching the filesystem provider is a path, and
 * a traversal sequence in one would write outside the backup directory.
 */
const KEY_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/-]{0,200}$/;

export function assertSafeStorageKey(key: string): string {
  if (!KEY_PATTERN.test(key)) {
    throw new Error('That backup storage key is not valid.');
  }
  // Checked separately from the pattern so the intent is explicit: no segment
  // may be "." or "..", and no key may be absolute.
  if (key.startsWith('/') || key.split('/').some((part) => part === '.' || part === '..')) {
    throw new Error('That backup storage key is not valid.');
  }
  return key;
}
